IAEC-714 & 715
cid-harvard/classifications pull request #1
Opened 2018-04-06 17:40 UTC by bleonard33

Add the services classification to the HS and SITC hierarchies

2018-04-06 17:55 UTC, makmanalp requested changes
Looks good, one minor change!

2018-04-06 17:55 UTC, makmanalp commented on product/HS/IntlAtlas/clean.py
> +    parent_id_table = parent_id_table.append(services).sort_index()
Sweet, didn't know about `sort_index`.

2018-04-06 17:55 UTC, makmanalp commented on product/HS/IntlAtlas/in/Services_Hierarchy.tsv
> +code	name	level	name_en	name_es	name_short_en	name_short_es	parent_idServices	Services	section	Services	Services	Services	Services	Other	Other	2digit	Other	Other	Other	Other	0Travel services	Trave
Not a big deal but looks like the services input files have weird line terminators (`\r` / `^M`), would be nice to switch to using `\n` like everything else.

2018-04-06 18:07 UTC, bleonard33 commented
Verison bumped and EOL characters switched to unix instead of macos 👍

2018-04-09 18:15 UTC, makmanalp approved these changes

2018-04-09 18:16 UTC, merged